### ISSUE TITLE
Is ParaDiffusion code going to be released?

### ISSUE THREAD

**Issue by Njasa2k** [weijiawu/ParaDiffusion#3]

**Comment by weijiawu** [comment]
The code will be open-sourced by the end of March. Thank you for your interest.

**Comment by Kimiko-AI** [comment]
Thank for your work

**Comment by olliacc** [comment]
> The code will be open-sourced by the end of March. Thank you for your interest.

Is there an update on this?

**Comment by TruthSearcher** [comment]
> The code will be open-sourced by the end of March. Thank you for your interest.

can we also get an open-source license for the repo?

**Comment by weijiawu** [comment]
> > The code will be open-sourced by the end of March. Thank you for your interest.
> 
> can we also get an open-source license for the repo?

The license will be set to MIT license(https://github.com/anonymous-pits/pits/blob/main/LICENSE) or Apache license(https://github.com/facebookresearch/segment-anything?tab=Apache-2.0-1-ov-file). Hope this can help you.
