### ISSUE TITLE
question about the released model--SDXL or SD1.x ?

### ISSUE THREAD

**Issue by D222097** [weijiawu/ParaDiffusion#6]
Wrote in the paper：
> For the diffusion model, we follow SDXL [23] and use a Unet of 1.3B parameters to learn the latent Gaussian noise.

But in the released model unet config file:
> "block_out_channels": [ 384, 768, 1152, 1536],

Could I assume that you finetune on SDXL actually and only release the 1.x version?

**Comment by weijiawu** [comment]
We did not fine-tune for SDXL. As shown in Figure 2, this work represents a training process of a foundation model. In fact, our UNet architecture is based on https://github.com/ai-forever/Kandinsky-2, and the text encoder is llama v2. The training was implemented from scratch.

**Comment by D222097** [comment]
Thanks for your detailed reply. It's been very helpful.

**Comment by weijiawu** [comment]
> Thanks for your detailed reply. It's been very helpful.
You're welcome
